import jsPDF from 'jspdf';
import 'jspdf-autotable';

export function generateInvoice(job, settings, presets) {
  const doc = new jsPDF();
  const blue = [59, 130, 246];
  const dark = [15, 23, 42];
  const W = doc.internal.pageSize.getWidth();

  // Top accent bar
  doc.setFillColor(...blue);
  doc.rect(0, 0, W, 8, 'F');

  // Logo
  let y = 20;
  const logo = settings.logo;
  if (logo) {
    try { doc.addImage(logo, 'PNG', 14, y, 30, 30); } catch (_) { /* skip */ }
  }

  // Business info
  const nameX = logo ? 50 : 14;
  doc.setFontSize(22).setFont(undefined, 'bold').setTextColor(...dark);
  doc.text(settings.businessName || 'My Business', nameX, y + 8);
  doc.setFontSize(10).setFont(undefined, 'normal').setTextColor(100, 116, 139);
  if (settings.businessPhone) doc.text(settings.businessPhone, nameX, y + 16);
  if (settings.businessEmail) doc.text(settings.businessEmail, nameX, y + 22);

  // INVOICE label
  doc.setFontSize(28).setFont(undefined, 'bold').setTextColor(...blue);
  doc.text('INVOICE', W - 14, y + 8, { align: 'right' });

  // Invoice meta
  y = 60;
  doc.setFontSize(10).setFont(undefined, 'normal').setTextColor(100, 116, 139);
  doc.text(`Invoice #: FD-${String(job.id).padStart(4, '0')}`, W - 14, y, { align: 'right' });
  doc.text(`Date: ${new Date(job.timestamp).toLocaleDateString()}`, W - 14, y + 6, { align: 'right' });

  // Client
  doc.setFontSize(12).setFont(undefined, 'bold').setTextColor(...dark);
  doc.text('Bill To:', 14, y);
  doc.setFont(undefined, 'normal');
  doc.text(job.clientName || 'Walk-in Customer', 14, y + 7);
  if (job.clientPhone) doc.text(job.clientPhone, 14, y + 13);
  if (job.vehicle) doc.text(job.vehicle, 14, y + 19);

  // Line items table
  y += 30;
  const items = (job.services || []).map(s => {
    const preset = presets.find(p => p.id === s.presetId);
    return [preset?.name || s.name || 'Service', `$${Number(s.price).toFixed(2)}`];
  });

  doc.autoTable({
    startY: y,
    head: [['Service', 'Amount']],
    body: items.length ? items : [['Service', '$0.00']],
    theme: 'grid',
    headStyles: { fillColor: blue, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 11 },
    bodyStyles: { textColor: dark, fontSize: 11 },
    columnStyles: { 1: { halign: 'right', cellWidth: 40 } },
    margin: { left: 14, right: 14 },
  });

  // Total
  const totalY = doc.lastAutoTable.finalY + 10;
  const total = (job.services || []).reduce((s, x) => s + Number(x.price || 0), 0);
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(W - 90, totalY - 6, 76, 22, 3, 3, 'F');
  doc.setFontSize(14).setFont(undefined, 'bold').setTextColor(...dark);
  doc.text(`Total: $${total.toFixed(2)}`, W - 14, totalY + 8, { align: 'right' });

  // Pay Now button
  const stripeLink = settings.stripeLink;
  if (stripeLink) {
    const btnY = totalY + 30;
    doc.setFillColor(...blue);
    doc.roundedRect(W / 2 - 40, btnY, 80, 14, 4, 4, 'F');
    doc.setFontSize(13).setFont(undefined, 'bold').setTextColor(255, 255, 255);
    doc.text('Pay Now', W / 2, btnY + 10, { align: 'center' });
    doc.link(W / 2 - 40, btnY, 80, 14, { url: stripeLink });
  }

  // Footer
  const footY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8).setFont(undefined, 'normal').setTextColor(148, 163, 184);
  doc.text('Generated by FlashDash', W / 2, footY, { align: 'center' });

  return doc;
}
